services:
  stomp-server:
    image: hub.osg-htc.org/mwestphall/stomp-server
    build:
      context: ../../stomp-server-go
    command: stomp-server-go --port 8080
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:8080"

  server-ui:
    image: hub.osg-htc.org/mwestphall/stomp-server-ui
    build:
      context: ../../server-ui
    restart: unless-stopped
    ports:
      - "${UI_PORT:-8001}:8000"
